/** 可本地化的名称条目，用于稳定配置引用与中英文显示。 */
export type LocalizedNameEntry = { id: string; en: string; zh: string };

/** 国家名称主体池；国家生成时会与政体池随机组合。 */
export const nationNameBases: LocalizedNameEntry[] = [
  { id: "aurora", en: "Aurora", zh: "极光" }, { id: "verdant", en: "Verdant", zh: "苍翠" },
  { id: "sol", en: "Sol", zh: "曜日" }, { id: "ember", en: "Ember", zh: "余烬" },
  { id: "lumen", en: "Lumen", zh: "流明" }, { id: "cobalt", en: "Cobalt", zh: "苍蓝" },
  { id: "meridian", en: "Meridian", zh: "子午" }, { id: "horizon", en: "Horizon", zh: "地平" },
  { id: "silver", en: "Silver", zh: "白银" }, { id: "river", en: "River", zh: "长河" },
  { id: "crown", en: "Crown", zh: "王冠" }, { id: "aster", en: "Aster", zh: "星芒" },
];

/** 国家政体池；与名称主体组合形成完整国家名。 */
export const governmentForms: LocalizedNameEntry[] = [
  { id: "republic", en: "Republic", zh: "共和国" }, { id: "federation", en: "Federation", zh: "联邦" },
  { id: "kingdom", en: "Kingdom", zh: "王国" }, { id: "empire", en: "Empire", zh: "帝国" },
  { id: "directorate", en: "Directorate", zh: "统合体" }, { id: "commonwealth", en: "Commonwealth", zh: "共同体" },
  { id: "league", en: "League", zh: "联盟" }, { id: "assembly", en: "Assembly", zh: "议会国" },
];

/** 省份完整名称池；生成世界时按种子打乱并逐一抽取，确保同一世界内名称不重复。 */
export const provinceNames: LocalizedNameEntry[] = [
  ["northreach", "Northreach", "北境"], ["southmere", "Southmere", "南湖"],
  ["eastvale", "Eastvale", "东谷"], ["westmarch", "Westmarch", "西疆"],
  ["highplain", "Highplain", "高原"], ["lowfen", "Lowfen", "低泽"],
  ["oldwood", "Oldwood", "古林"], ["newford", "Newford", "新津"],
  ["redridge", "Redridge", "赤岭"], ["bluebasin", "Bluebasin", "蓝盆地"],
  ["silvercoast", "Silvercoast", "银海岸"], ["goldfield", "Goldfield", "金野"],
  ["greenmoor", "Greenmoor", "翠原"], ["blackpass", "Blackpass", "黑隘"],
  ["whiteharbor", "Whiteharbor", "白港"], ["clearwater", "Clearwater", "清水"],
  ["brightfall", "Brightfall", "明瀑"], ["deepwatch", "Deepwatch", "深望"],
  ["stormgate", "Stormgate", "风暴门"], ["cloudrest", "Cloudrest", "云憩"],
  ["starplain", "Starplain", "星原"], ["moonvale", "Moonvale", "月谷"],
  ["sunreach", "Sunreach", "日境"], ["stoneford", "Stoneford", "石津"],
  ["ironmarch", "Ironmarch", "铁疆"], ["copperhill", "Copperhill", "铜岭"],
  ["jadebasin", "Jadebasin", "玉盆地"], ["pearlcoast", "Pearlcoast", "珠岸"],
  ["amberfield", "Amberfield", "琥珀野"], ["crystalmoor", "Crystalmoor", "晶原"],
  ["frostpass", "Frostpass", "霜隘"], ["snowharbor", "Snowharbor", "雪港"],
  ["rainwater", "Rainwater", "雨水"], ["mistfall", "Mistfall", "雾瀑"],
  ["dawnwatch", "Dawnwatch", "曙望"], ["duskgate", "Duskgate", "暮门"],
  ["windrest", "Windrest", "风息"], ["thunderplain", "Thunderplain", "雷原"],
  ["riverdale", "Riverdale", "河谷"], ["lakevale", "Lakevale", "湖谷"],
  ["ashreach", "Ashreach", "灰境"], ["pinewood", "Pinewood", "松林"],
  ["oakford", "Oakford", "橡津"], ["wolfmarch", "Wolfmarch", "狼疆"],
  ["falconridge", "Falconridge", "鹰岭"], ["ravenbasin", "Ravenbasin", "鸦盆地"],
  ["lioncoast", "Lioncoast", "狮岸"], ["stagfield", "Stagfield", "鹿野"],
  ["foxmoor", "Foxmoor", "狐原"], ["bearpass", "Bearpass", "熊隘"],
  ["eagleharbor", "Eagleharbor", "鹰港"], ["willowwater", "Willowwater", "柳水"],
  ["maplefall", "Maplefall", "枫瀑"], ["cedarwatch", "Cedarwatch", "杉望"],
  ["birchgate", "Birchgate", "桦门"], ["elmrest", "Elmrest", "榆憩"],
  ["roseplain", "Roseplain", "蔷薇原"], ["lilyvale", "Lilyvale", "百合谷"],
  ["lotusreach", "Lotusreach", "莲境"], ["reedwood", "Reedwood", "芦林"],
  ["sandford", "Sandford", "沙津"], ["saltmarch", "Saltmarch", "盐疆"],
  ["flintridge", "Flintridge", "燧石岭"], ["claybasin", "Claybasin", "陶土盆地"],
  ["coralcoast", "Coralcoast", "珊瑚岸"], ["wheatfield", "Wheatfield", "麦野"],
  ["heathermoor", "Heathermoor", "石楠原"], ["emberpass", "Emberpass", "余烬隘"],
  ["coalharbor", "Coalharbor", "煤港"], ["springwater", "Springwater", "春水"],
  ["shadowfall", "Shadowfall", "影落"], ["crownwatch", "Crownwatch", "王冠望"],
  ["kingsgate", "Kingsgate", "王门"], ["queensrest", "Queensrest", "王后憩"],
  ["nobleplain", "Nobleplain", "贵族原"], ["freemenvale", "Freemenvale", "自由民谷"],
  ["templereach", "Templereach", "神殿境"], ["abbeywood", "Abbeywood", "修院林"],
  ["marketford", "Marketford", "市集津"], ["guildmarch", "Guildmarch", "行会疆"],
  ["auroraridge", "Auroraridge", "极光岭"], ["meridianbasin", "Meridianbasin", "子午盆地"],
  ["horizoncoast", "Horizoncoast", "地平岸"], ["lumenfield", "Lumenfield", "流明野"],
  ["cobaltmoor", "Cobaltmoor", "苍蓝原"], ["verdantpass", "Verdantpass", "苍翠隘"],
  ["solharbor", "Solharbor", "曜日港"], ["asterwater", "Asterwater", "星芒水"],
  ["crownfall", "Crownfall", "王冠落"], ["emberwatch", "Emberwatch", "余烬望"],
  ["rivergate", "Rivergate", "长河门"], ["silverrest", "Silverrest", "白银憩"],
  ["goldenplain", "Goldenplain", "黄金原"], ["azurevale", "Azurevale", "天蓝谷"],
  ["crimsonreach", "Crimsonreach", "绯红境"], ["ivorywood", "Ivorywood", "象牙林"],
  ["obsidianford", "Obsidianford", "黑曜津"], ["marblemarch", "Marblemarch", "大理石疆"],
  ["graniteridge", "Graniteridge", "花岗岭"], ["quartzbasin", "Quartzbasin", "石英盆地"],
  ["sapphirecoast", "Sapphirecoast", "蓝宝石岸"], ["rubyfield", "Rubyfield", "红宝石野"],
  ["emeraldmoor", "Emeraldmoor", "翡翠原"], ["topazpass", "Topazpass", "黄玉隘"],
  ["opalharbor", "Opalharbor", "欧泊港"], ["onyxwater", "Onyxwater", "缟玛瑙水"],
  ["garnetfall", "Garnetfall", "石榴石落"], ["amethystwatch", "Amethystwatch", "紫晶望"],
  ["diamondgate", "Diamondgate", "钻石门"], ["bronzerest", "Bronzerest", "青铜憩"],
  ["laurelplain", "Laurelplain", "月桂原"], ["cypressvale", "Cypressvale", "柏谷"],
  ["olivereach", "Olivereach", "橄榄境"], ["orchardwood", "Orchardwood", "果园林"],
  ["vineyardford", "Vineyardford", "葡萄津"], ["meadowmarch", "Meadowmarch", "草甸疆"],
  ["highlandridge", "Highlandridge", "高地岭"], ["lowlandbasin", "Lowlandbasin", "低地盆地"],
  ["frontiercoast", "Frontiercoast", "边疆岸"], ["heartlandfield", "Heartlandfield", "腹地"],
  ["wildmoor", "Wildmoor", "荒原"], ["farpass", "Farpass", "远隘"],
  ["safeharbor", "Safeharbor", "安港"], ["sweetwater", "Sweetwater", "甘泉"],
  ["longfall", "Longfall", "长瀑"], ["farwatch", "Farwatch", "远望"],
  ["irongate", "Irongate", "铁门"], ["havenrest", "Havenrest", "安息地"],
  ["grandplain", "Grandplain", "大平原"], ["fairvale", "Fairvale", "秀谷"],
].map(([id, en, zh]) => ({ id, en, zh }));

/** 城市完整名称池；生成时直接抽取，方便策划人员维护。 */
export const cityNames: LocalizedNameEntry[] = [
  ["starhaven", "Starhaven", "星港"], ["rivergate", "Rivergate", "河门"], ["ironford", "Ironford", "铁津"],
  ["brightspire", "Brightspire", "辉塔"], ["cloudrest", "Cloudrest", "云栖"], ["emberfall", "Emberfall", "烬落"],
  ["lumenbridge", "Lumenbridge", "光桥"], ["cobaltport", "Cobaltport", "苍蓝港"], ["greenwatch", "Greenwatch", "翠望"],
  ["goldenfield", "Goldenfield", "金原"], ["stonehold", "Stonehold", "石垒"], ["moonmarket", "Moonmarket", "月集"],
  ["sunward", "Sunward", "向阳城"], ["stormrest", "Stormrest", "息风城"], ["clearwater", "Clearwater", "清泉"],
  ["highgarden", "Highgarden", "高庭"], ["silvercross", "Silvercross", "银渡"], ["newforge", "Newforge", "新炉城"],
  ["redharbor", "Redharbor", "赤港"], ["northpoint", "Northpoint", "北岬"], ["southvale", "Southvale", "南谷"],
  ["eastmere", "Eastmere", "东湖"], ["westcrown", "Westcrown", "西冠"], ["deepwood", "Deepwood", "幽林"],
  ["auricgate", "Auricgate", "鎏金门"], ["horizonfall", "Horizonfall", "天际城"], ["meridian", "Meridian", "子午城"],
  ["nova", "Nova", "新星城"], ["asterforge", "Asterforge", "星炉"], ["crownrest", "Crownrest", "冠栖"],
  ["verdantford", "Verdantford", "翠津"], ["solhaven", "Solhaven", "曜日港"], ["frostwatch", "Frostwatch", "霜望"],
  ["dawngate", "Dawngate", "曙门"], ["mistbridge", "Mistbridge", "雾桥"], ["oakheart", "Oakheart", "橡心城"],
  ["sandspire", "Sandspire", "沙塔"], ["blackfen", "Blackfen", "玄泽"], ["whitecliff", "Whitecliff", "白崖"],
  ["bluegarden", "Bluegarden", "蓝庭"], ["sunforge", "Sunforge", "日炉"], ["moonford", "Moonford", "月津"],
  ["starbridge", "Starbridge", "星桥"], ["rainhaven", "Rainhaven", "雨港"], ["windrest", "Windrest", "风息城"],
  ["pinewatch", "Pinewatch", "松望"], ["ashmarket", "Ashmarket", "灰集"], ["crystalbay", "Crystal Bay", "晶湾"],
  ["falconreach", "Falconreach", "鹰境"], ["jadegate", "Jadegate", "玉门"], ["pearlhaven", "Pearlhaven", "珠港"],
  ["thunderford", "Thunderford", "雷津"], ["willowrest", "Willowrest", "柳栖"], ["wolfpoint", "Wolfpoint", "狼岬"],
].map(([id, en, zh]) => ({ id, en, zh }));
